apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8096
      protocol: TCP
      name: http
  selector:
    app: jellyfin